use proc_macro::TokenStream;
use proc_macro2::{Span, TokenStream as TokenStream2};
use quote::quote;
use syn::{
    Data, DeriveInput, Expr, Fields, GenericParam, LitStr, Token, Type, parse::ParseStream,
    parse_macro_input,
};

/// Derive [`Dimension`](::yadc::Dimension) for a named-field struct.
///
/// Numeric fields are interpreted as dimension exponents; any single field
/// annotated `#[kind]` carries a user-defined Kind enum.
///
/// Emitted for the struct:
/// - `impl ConstParamTy_ + StructuralPartialEq for Dim`
/// - `impl const PartialEq + Eq for Dim` — enables `==`/`!=` in const expressions.
/// - `impl const Mul + Div + Add + Sub for Dim` — dimensional arithmetic.
/// - `impl Dimension for Dim` — `ZERO`, `valid`, `numeric_eq`.
/// - Inherent const fns: `valid`, `numeric_eq`, `dims_eq` (value-based equality
///   for const generic expressions), `can_mul`, `can_div`, `can_add`, `can_sub`,
///   `can_add_assign`, `can_sub_assign`.
///
/// Users should add `#[derive(Debug)]` themselves — the derive no longer emits
/// one. `PartialEq` and `Eq` are generated by this derive and must not be
/// listed separately in `#[derive(...)]`.
///
/// ```ignore
/// #[derive(Copy, Clone, Debug, Dimension)]
/// pub struct Dim {
///     pub m: i8, pub kg: i8, pub s: i8,
///     #[kind] pub kind: Kind,
/// }
/// ```
#[proc_macro_derive(Dimension, attributes(kind))]
pub fn derive_dimension(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    expand_dimension(&input)
        .unwrap_or_else(|e| e.to_compile_error())
        .into()
}

/// Derive the dimensional **Kind** trait and combinator ops on an enum with
/// exactly five variants — one for each role: `Linear`, `Affine`, `Angle`,
/// `SolidAngle`, `Invalid`.
///
/// Variant names match roles by default; rename with `#[kind(<Role>)]` to use
/// custom identifiers (e.g. `#[kind(Linear)] Scalar`).
///
/// Emits:
/// - `impl ConstParamTy_ + StructuralPartialEq for Kind`
/// - `impl const PartialEq + Eq for Kind`
/// - `impl const Mul + Div + Add + Sub for Kind` — kind algebra tables.
/// - `impl yadc::traits::Kind for Kind` — `ZERO`, `INVALID`, `name()`.
///
/// The `DimensionDeserialize` derive uses serde to round-trip the kind tag;
/// add `#[derive(serde::Serialize, serde::Deserialize)]` to your Kind enum.
#[proc_macro_derive(Kind, attributes(kind))]
pub fn derive_kind(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    expand_kind(&input)
        .unwrap_or_else(|e| e.to_compile_error())
        .into()
}

// Generates ConstParamTy_, ZERO/INVALID consts, impl const PartialEq/Eq, and
// impl const Mul/Div/Add/Sub on an enum that represents a dimensional "kind".
// The five roles — Linear, Affine, Angle, SolidAngle, Invalid — must each be
// present, by matching variant name or via a #[kind(<Role>)] override.
fn expand_kind(input: &DeriveInput) -> syn::Result<TokenStream2> {
    let name = &input.ident;
    let variants = match &input.data {
        Data::Enum(e) => &e.variants,
        _ => {
            return Err(syn::Error::new_spanned(
                name,
                "#[derive(Kind)] only works on enums",
            ));
        }
    };

    const ROLES: [&str; 5] = ["Linear", "Affine", "Angle", "SolidAngle", "Invalid"];

    // role name → variant ident
    let mut role_map: std::collections::HashMap<&'static str, &syn::Ident> =
        std::collections::HashMap::new();

    for variant in variants {
        if !matches!(variant.fields, Fields::Unit) {
            return Err(syn::Error::new_spanned(
                variant,
                "#[derive(Kind)] variants must be unit variants",
            ));
        }
        // Look for #[kind(RoleName)] override.
        let mut role: Option<&'static str> = None;
        for attr in &variant.attrs {
            if attr.path().is_ident("kind") {
                let arg: syn::Ident = attr.parse_args()?;
                let s = arg.to_string();
                let matched = ROLES.iter().find(|r| **r == s).ok_or_else(|| {
                    syn::Error::new_spanned(
                        &arg,
                        "kind role must be one of: Linear, Affine, Angle, SolidAngle, Invalid",
                    )
                })?;
                role = Some(*matched);
                break;
            }
        }
        // Fall back to variant name matching a role.
        let role = role
            .or_else(|| {
                let n = variant.ident.to_string();
                ROLES.iter().find(|r| **r == n).copied()
            })
            .ok_or_else(|| {
                syn::Error::new_spanned(
                    variant,
                    format!(
                        "variant `{}` doesn't name a known kind role; add #[kind(<Role>)]",
                        variant.ident
                    ),
                )
            })?;
        if role_map.insert(role, &variant.ident).is_some() {
            return Err(syn::Error::new_spanned(
                variant,
                format!("duplicate kind role `{role}`"),
            ));
        }
    }

    // All roles must be assigned.
    let get = |r: &'static str| -> syn::Result<&syn::Ident> {
        role_map
            .get(r)
            .copied()
            .ok_or_else(|| syn::Error::new_spanned(name, format!("missing kind role `{r}`")))
    };
    let v_linear = get("Linear")?;
    let v_affine = get("Affine")?;
    let v_angle = get("Angle")?;
    let v_solid = get("SolidAngle")?;
    let v_invalid = get("Invalid")?;

    Ok(quote! {
        impl ::core::marker::ConstParamTy_ for #name {}
        impl ::core::marker::StructuralPartialEq for #name {}

        impl const ::core::cmp::PartialEq for #name {
            fn eq(&self, rhs: &Self) -> bool {
                matches!(
                    (*self, *rhs),
                    (#name::#v_linear, #name::#v_linear)
                        | (#name::#v_affine, #name::#v_affine)
                        | (#name::#v_angle, #name::#v_angle)
                        | (#name::#v_solid, #name::#v_solid)
                        | (#name::#v_invalid, #name::#v_invalid)
                )
            }
        }
        impl ::core::cmp::Eq for #name {}

        impl const ::core::ops::Mul for #name {
            type Output = Self;
            fn mul(self, rhs: Self) -> Self {
                match (self, rhs) {
                    (#name::#v_invalid, _) | (_, #name::#v_invalid) => #name::#v_invalid,
                    (#name::#v_linear, k) | (k, #name::#v_linear) => k,
                    (#name::#v_angle, #name::#v_angle) => #name::#v_linear,
                    (#name::#v_solid, #name::#v_solid) => #name::#v_linear,
                    _ => #name::#v_invalid,
                }
            }
        }

        impl const ::core::ops::Div for #name {
            type Output = Self;
            fn div(self, rhs: Self) -> Self {
                match (self, rhs) {
                    (#name::#v_invalid, _) | (_, #name::#v_invalid) => #name::#v_invalid,
                    (k, #name::#v_linear) => k,
                    (#name::#v_affine, #name::#v_affine) => #name::#v_linear,
                    (#name::#v_angle, #name::#v_angle) => #name::#v_linear,
                    (#name::#v_solid, #name::#v_solid) => #name::#v_linear,
                    _ => #name::#v_invalid,
                }
            }
        }

        impl const ::core::ops::Add for #name {
            type Output = Self;
            fn add(self, rhs: Self) -> Self {
                match (self, rhs) {
                    (#name::#v_invalid, _) | (_, #name::#v_invalid) => #name::#v_invalid,
                    (#name::#v_linear, #name::#v_linear) => #name::#v_linear,
                    (#name::#v_affine, #name::#v_linear) | (#name::#v_linear, #name::#v_affine)
                        => #name::#v_affine,
                    (#name::#v_affine, #name::#v_affine) => #name::#v_invalid,
                    (#name::#v_angle, #name::#v_angle) => #name::#v_angle,
                    (#name::#v_solid, #name::#v_solid) => #name::#v_solid,
                    _ => #name::#v_invalid,
                }
            }
        }

        impl const ::core::ops::Sub for #name {
            type Output = Self;
            fn sub(self, rhs: Self) -> Self {
                match (self, rhs) {
                    (#name::#v_invalid, _) | (_, #name::#v_invalid) => #name::#v_invalid,
                    (#name::#v_linear, #name::#v_linear) => #name::#v_linear,
                    (#name::#v_affine, #name::#v_linear) => #name::#v_affine,
                    (#name::#v_affine, #name::#v_affine) => #name::#v_linear,
                    (#name::#v_angle, #name::#v_angle) => #name::#v_angle,
                    (#name::#v_solid, #name::#v_solid) => #name::#v_solid,
                    _ => #name::#v_invalid,
                }
            }
        }

        impl ::yadc::traits::Kind for #name {
            const ZERO: Self = #name::#v_linear;
            const INVALID: Self = #name::#v_invalid;
            const ANGLE: Self = #name::#v_angle;
            const SOLID_ANGLE: Self = #name::#v_solid;

            fn name(self) -> &'static str {
                match self {
                    #name::#v_linear  => ::core::stringify!(#v_linear),
                    #name::#v_affine  => ::core::stringify!(#v_affine),
                    #name::#v_angle   => ::core::stringify!(#v_angle),
                    #name::#v_solid   => ::core::stringify!(#v_solid),
                    #name::#v_invalid => ::core::stringify!(#v_invalid),
                }
            }

            fn ucum_prefix(self) -> ::core::option::Option<&'static str> {
                match self {
                    #name::#v_angle => ::core::option::Option::Some("rad"),
                    #name::#v_solid => ::core::option::Option::Some("sr"),
                    _ => ::core::option::Option::None,
                }
            }
        }
    })
}

fn expand_dimension(input: &DeriveInput) -> syn::Result<TokenStream2> {
    let name = &input.ident;

    let fields = match &input.data {
        Data::Struct(s) => match &s.fields {
            Fields::Named(f) => &f.named,
            _ => {
                return Err(syn::Error::new_spanned(
                    name,
                    "#[derive(Dimension)] requires a struct with named fields",
                ));
            }
        },
        _ => {
            return Err(syn::Error::new_spanned(
                name,
                "#[derive(Dimension)] only works on structs",
            ));
        }
    };

    // Partition fields into "numeric" (i8/i16/.. exponents) and "kind" (marked
    // with #[kind] — at most one). Kind field uses .mul/.div/.add/.sub/.eq
    // methods and a ::ZERO + ::INVALID constant on its type.
    let mut numeric_fields: Vec<&syn::Field> = Vec::new();
    let mut kind_field: Option<&syn::Field> = None;
    for f in fields.iter() {
        if f.attrs.iter().any(|a| a.path().is_ident("kind")) {
            if kind_field.is_some() {
                return Err(syn::Error::new_spanned(f, "only one #[kind] field allowed"));
            }
            kind_field = Some(f);
        } else {
            numeric_fields.push(f);
        }
    }

    let num_idents: Vec<&syn::Ident> = numeric_fields
        .iter()
        .filter_map(|f| f.ident.as_ref())
        .collect();

    // dims_mul: numerics +, kind .mul   (Qty Mul output)
    // dims_div: numerics -, kind .div   (Qty Div output)
    // dims_add: numerics from a, kind .add  (Qty Add output; numerics-must-match)
    // dims_sub: numerics from a, kind .sub  (Qty Sub output; numerics-must-match)
    let mul_inits: Vec<_> = num_idents
        .iter()
        .map(|f| quote! { #f: a.#f + b.#f })
        .collect();
    let div_inits: Vec<_> = num_idents
        .iter()
        .map(|f| quote! { #f: a.#f - b.#f })
        .collect();
    let copy_inits: Vec<_> = num_idents.iter().map(|f| quote! { #f: a.#f }).collect();
    let zero_inits: Vec<_> = num_idents.iter().map(|f| quote! { #f: 0 }).collect();

    let (kind_mul, kind_div, kind_add_, kind_sub_, kind_zero, kind_eq_clause, kind_valid_body) =
        if let Some(kf) = kind_field {
            let k = kf.ident.as_ref().unwrap();
            let kty = &kf.ty;
            (
                quote! { , #k: a.#k * b.#k },
                quote! { , #k: a.#k / b.#k },
                quote! { , #k: a.#k + b.#k },
                quote! { , #k: a.#k - b.#k },
                quote! { , #k: <#kty as ::yadc::traits::Kind>::ZERO },
                quote! { && self.#k == other.#k },
                quote! { self.#k != <#kty as ::yadc::traits::Kind>::INVALID },
            )
        } else {
            (
                quote! {},
                quote! {},
                quote! {},
                quote! {},
                quote! {},
                quote! {},
                quote! { true },
            )
        };

    Ok(quote! {
        impl ::core::marker::ConstParamTy_ for #name {}
        impl ::core::marker::StructuralPartialEq for #name {}

        impl const ::core::cmp::PartialEq for #name {
            fn eq(&self, other: &Self) -> bool {
                true #(&& self.#num_idents == other.#num_idents)* #kind_eq_clause
            }
        }
        impl ::core::cmp::Eq for #name {}

        impl const ::core::ops::Mul for #name {
            type Output = Self;
            fn mul(self, rhs: Self) -> Self {
                let (a, b) = (self, rhs);
                #name { #(#mul_inits),* #kind_mul }
            }
        }
        impl const ::core::ops::Div for #name {
            type Output = Self;
            fn div(self, rhs: Self) -> Self {
                let (a, b) = (self, rhs);
                #name { #(#div_inits),* #kind_div }
            }
        }
        impl const ::core::ops::Add for #name {
            type Output = Self;
            #[allow(unused_variables)]
            fn add(self, b: Self) -> Self {
                let a = self;
                #name { #(#copy_inits),* #kind_add_ }
            }
        }
        impl const ::core::ops::Sub for #name {
            type Output = Self;
            #[allow(unused_variables)]
            fn sub(self, b: Self) -> Self {
                let a = self;
                #name { #(#copy_inits),* #kind_sub_ }
            }
        }

        impl #name {
            pub const fn valid(self) -> bool {
                #kind_valid_body
            }
            pub const fn numeric_eq(self, other: Self) -> bool {
                true #(&& self.#num_idents == other.#num_idents)*
            }
            // Value-based equality for use in const generic expressions where
            // the `==` operator's `&self` borrows are not permitted.
            pub const fn dims_eq(self, other: Self) -> bool {
                true #(&& self.#num_idents == other.#num_idents)* #kind_eq_clause
            }
            pub const fn can_mul(self, b: Self) -> bool {
                (self * b).valid()
            }
            pub const fn can_div(self, b: Self) -> bool {
                (self / b).valid()
            }
            pub const fn can_add(self, b: Self) -> bool {
                self.numeric_eq(b) && (self + b).valid()
            }
            pub const fn can_sub(self, b: Self) -> bool {
                self.numeric_eq(b) && (self - b).valid()
            }
            pub const fn can_add_assign(self, b: Self) -> bool {
                self.numeric_eq(b) && (self + b).dims_eq(self)
            }
            pub const fn can_sub_assign(self, b: Self) -> bool {
                self.numeric_eq(b) && (self - b).dims_eq(self)
            }
        }

        impl ::yadc::Dimension for #name {
            const ZERO: Self = #name { #(#zero_inits),* #kind_zero };
            fn valid(self) -> bool { self.valid() }
            fn numeric_eq(self, other: Self) -> bool { self.numeric_eq(other) }
        }
    })
}

/// Derive [`Unit`](::yadc::Unit) for a unit enum.
///
/// `Copy` and `Clone` are NOT generated — add them to `#[derive(...)]`
/// yourself (the `Unit` trait requires `Copy`).
///
/// Each variant carries one of these `#[unit(...)]` forms (the long-form
/// string is required):
/// - `#[unit(multiplier, "symbol", "long")]`
/// - `#[unit(multiplier, "symbol", "long", offset)]`
///
/// Positional `long` is a string literal at position 3; positional `offset`
/// is any other expression. Keyword form (`offset = N`, `long = "..."`) is
/// also accepted.
///
/// Enum-level attributes:
/// - `#[dim(QtyAlias)]` (required) — names the `StaticQuantity` type alias the
///   unit belongs to (becomes [`Unit::Offset`](::yadc::Unit::Offset)).
/// - `#[dim_delta(LinearQtyAlias)]` (optional) — for affine units like
///   `Celsius`, points at the Linear "delta" type
///   (becomes [`Unit::Multiplier`](::yadc::Unit::Multiplier)). Omitted =
///   `Multiplier = Offset`, correct for pure-linear units.
///
/// ```ignore
/// #[derive(Unit)]
/// #[dim(Mass)]
/// pub enum MassUnit {
///     #[unit(1.0, "kg", "kilograms")]   Kilogram,
///     #[unit(0.001, "g", "grams")]      Gram,
/// }
///
/// #[derive(Unit)]
/// #[dim(Temperature)]
/// #[dim_delta(TemperatureDelta)]
/// pub enum TempUnit {
///     #[unit(1.0, "K", "kelvin")]                Kelvin,
///     #[unit(1.0, "°C", "celsius", 273.15)]      Celsius,
/// }
/// ```
#[proc_macro_derive(Unit, attributes(dim, dim_delta, unit))]
pub fn derive_unit(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    expand_unit(&input)
        .unwrap_or_else(|e| e.to_compile_error())
        .into()
}

fn expand_unit(input: &DeriveInput) -> syn::Result<TokenStream2> {
    let name = &input.ident;

    // `#[dim(QtyType)]` — the Offset type (carries the unit's full kind,
    // e.g. `Temperature` for `Celsius`). Required.
    let qty_ty = find_attr_type(input, "dim")?.ok_or_else(|| {
        syn::Error::new_spanned(name, "missing #[dim(StaticQuantityAlias)] on unit enum")
    })?;
    // `#[dim_delta(LinearQtyType)]` — the Multiplier type, the Linear-kind
    // "delta" version of the unit's quantity. Optional; defaults to the
    // Offset type, which is correct for pure-linear units (Length, Mass).
    // Affine units (Celsius, Fahrenheit) must specify a separate delta
    // (e.g. `TemperatureDelta`) since multiplier is a slope (Linear) while
    // offset is a reference point (Affine).
    let delta_ty = find_attr_type(input, "dim_delta")?.unwrap_or_else(|| qty_ty.clone());

    let variants = match &input.data {
        Data::Enum(e) => &e.variants,
        _ => {
            return Err(syn::Error::new_spanned(
                name,
                "#[derive(Unit)] only works on enums",
            ));
        }
    };

    let mut mult_arms = Vec::new();
    let mut offset_arms = Vec::new();
    let mut symbol_arms = Vec::new();
    let mut long_arms = Vec::new();

    for variant in variants {
        let ident = &variant.ident;
        let (mult, symbol, offset_factor, long) = find_unit_attr(variant)?.ok_or_else(|| {
            syn::Error::new_spanned(ident, "missing #[unit(multiplier, \"symbol\")] on variant")
        })?;
        mult_arms.push(quote! {
            Self::#ident => <#delta_ty as ::yadc::StaticQuantity>::unit() * (#mult),
        });
        symbol_arms.push(quote! { Self::#ident => #symbol, });
        let long_str = long.ok_or_else(|| {
            syn::Error::new_spanned(
                ident,
                "missing long-form string in #[unit(multiplier, \"symbol\", \"long\")]",
            )
        })?;
        long_arms.push(quote! { Self::#ident => #long_str, });
        if let Some(factor) = offset_factor {
            offset_arms.push(quote! {
                Self::#ident => <#qty_ty as ::yadc::StaticQuantity>::unit() * ((#mult) * (#factor)),
            });
        } else {
            offset_arms.push(quote! { Self::#ident => <#qty_ty>::zero(), });
        }
    }

    Ok(quote! {
        impl ::yadc::Unit for #name {
            type D = <#qty_ty as ::yadc::StaticQuantity>::D;
            type V = <#qty_ty as ::yadc::StaticQuantity>::V;
            type Multiplier = #delta_ty;
            type Offset = #qty_ty;
            const DIM: Self::D = <#qty_ty>::DIM;
            fn multiplier(&self) -> Self::Multiplier { match self { #(#mult_arms)* } }
            fn offset(&self)     -> Self::Offset     { match self { #(#offset_arms)* } }
            fn symbol(&self) -> &'static str { match self { #(#symbol_arms)* } }
            fn long(&self)   -> &'static str { match self { #(#long_arms)* } }
        }
    })
}

/// Derive [`StaticQuantity`](::yadc::StaticQuantity), arithmetic operators, and
/// supporting inherent items for a tuple struct with one const-generic
/// `Dimension` parameter.
///
/// Emitted impls:
/// - `Copy`, `Clone`, `PartialEq`.
/// - `StaticQuantity` trait — exposes `D`, `V`, `DIM`; `from_unit` /
///   `as_unit` / `fmt_as_unit` come from the trait defaults (no per-`Qty<D>`
///   bodies emitted).
/// - `CanUseWithUnit<U>` blanket impl gated on
///   `Assert<{ <D>::dims_eq(U::DIM, D) }>: IsTrue` — this is what makes the
///   compile-time dim-value check on `from_unit` / `as_unit` work.
/// - `Deref<Target = V>` for `Qty<{ D::ZERO }>` — bare deref on dimensionless
///   quantities so the default `as_unit` body can unwrap the final
///   `Dimensionless<V>` to plain `V`.
/// - `Display` and `Debug` that print `value` followed by the `Debug` of the
///   dim when non-zero.
/// - `Mul`/`Div`/`Add`/`Sub` (cross-dim where applicable) — with dimension
///   composition through the user's [`Dim`](macro@Dimension) tables, guarded
///   by compile-time `Assert<{ ... }>: IsTrue` predicates.
/// - Scalar `Mul<V>` / `Div<V>`.
/// - `Default` and `Neg` when `Qty<D> += Qty<D>` is valid.
/// - `Sum<Qty<D>>` / `Sum<&Qty<D>>` when `Qty<D> += Qty<D>` is valid.
/// - Borrowed `AddAssign` / `SubAssign`, `PartialOrd`, and dimensionless
///   `MulAssign` / `DivAssign`.
/// - `StaticQuantity::unit() -> Self` — the multiplicative identity. Used by
///   the [`Unit`](macro@Unit) derive to construct multiplier/offset values
///   through type aliases (since `Length(1.0)` doesn't parse — type aliases
///   aren't tuple-struct constructors — but `<Length as StaticQuantity>::unit()
///   * V` composes via `Mul<V>`).
///
/// ```ignore
/// #[derive(StaticQuantity)]
/// pub struct Qty<const D: Dim>(f64);
/// ```
#[proc_macro_derive(StaticQuantity, attributes(dim, identities))]
pub fn derive_static_quantity(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    expand_quantity(&input)
        .unwrap_or_else(|e| e.to_compile_error())
        .into()
}

// Returns (one_expr, zero_expr) token streams for the `#[identities(one=..., zero=...)]`
// attribute. Falls back to the float literals `1.0` / `0.0` when the attribute is absent —
// those work for f64 and fail at compile time for custom V, pointing users to the attribute.
fn parse_identities(input: &DeriveInput) -> syn::Result<(TokenStream2, TokenStream2)> {
    for attr in &input.attrs {
        if attr.path().is_ident("identities") {
            let mut one: Option<Expr> = None;
            let mut zero: Option<Expr> = None;
            attr.parse_args_with(|buf: ParseStream<'_>| {
                while !buf.is_empty() {
                    let kw: syn::Ident = buf.parse()?;
                    buf.parse::<Token![=]>()?;
                    let val: Expr = buf.parse()?;
                    match kw.to_string().as_str() {
                        "one"  => one  = Some(val),
                        "zero" => zero = Some(val),
                        other  => return Err(syn::Error::new(
                            kw.span(),
                            format!("unknown `#[identities]` key `{other}`; expected `one` or `zero`"),
                        )),
                    }
                    if buf.peek(Token![,]) { buf.parse::<Token![,]>()?; }
                }
                Ok(())
            })?;
            let one_ts = one.map_or_else(|| quote! { 1.0 }, |e| quote! { #e });
            let zero_ts = zero.map_or_else(|| quote! { 0.0 }, |e| quote! { #e });
            return Ok((one_ts, zero_ts));
        }
    }
    Ok((quote! { 1.0 }, quote! { 0.0 }))
}

fn expand_quantity(input: &DeriveInput) -> syn::Result<TokenStream2> {
    let name = &input.ident;

    let value_ty = single_tuple_field(&input.data, name)?;
    let (d_ident, d_ty) = single_const_param(&input.generics, name)?;
    let (one_expr, zero_expr) = parse_identities(input)?;

    let qa = syn::Ident::new("__QA", Span::call_site());
    let qb = syn::Ident::new("__QB", Span::call_site());
    let u_ty = syn::Ident::new("__U", Span::call_site());

    Ok(quote! {
        impl<#u_ty, const #d_ident: #d_ty> ::yadc::CanUseWithUnit<#u_ty>
            for #name<#d_ident>
        where
            #u_ty: ::yadc::Unit<D = #d_ty, V = #value_ty>,
            ::yadc::Assert<
                { <#u_ty as ::yadc::Unit>::DIM.dims_eq(#d_ident) }
            >: ::yadc::IsTrue,
            #name<#d_ident>: ::core::ops::Sub<
                <#u_ty as ::yadc::Unit>::Offset,
                Output = <#u_ty as ::yadc::Unit>::Multiplier,
            >,
            <#u_ty as ::yadc::Unit>::Multiplier:
                ::core::ops::Add<<#u_ty as ::yadc::Unit>::Offset, Output = #name<#d_ident>>,
        {}

        impl<const #d_ident: #d_ty> ::yadc::StaticQuantity for #name<#d_ident> {
            type D = #d_ty;
            type V = #value_ty;
            fn unit() -> Self { Self(#one_expr) }
            // from_unit / as_unit / fmt_as_unit use trait defaults.
        }

        impl<const #d_ident: #d_ty> #name<#d_ident> {
            /// Additive identity (`V`'s "zero"). Used by the `Unit` derive for
            /// zero-offset unit arms. Override with `#[identities(zero = MyType(0.0))]`.
            pub fn zero() -> Self { Self(#zero_expr) }
        }

        impl<const #d_ident: #d_ty> #name<#d_ident> {
            pub const DIM: #d_ty = #d_ident;

            /// Construct from a value in `unit`. Inherent method — shadows both
            /// `StaticQuantity::from_unit` and `DynamicQuantity::from_unit` so
            /// that `Mass::from_unit(...)` remains unambiguous even though
            /// `Qty<D>` implements both traits.
            pub fn from_unit<#u_ty>(value: #value_ty, unit: #u_ty) -> Self
            where
                #u_ty: ::yadc::Unit<D = #d_ty, V = #value_ty>,
                Self: ::yadc::CanUseWithUnit<#u_ty>,
                <#u_ty as ::yadc::Unit>::Multiplier:
                    ::core::ops::Add<<#u_ty as ::yadc::Unit>::Offset, Output = Self>,
            {
                unit.multiplier() * value + unit.offset()
            }
        }

        impl ::core::convert::Into<#value_ty>
            for #name<{ <#d_ty as ::yadc::Dimension>::ZERO }>
        {
            fn into(self) -> #value_ty { self.0 }
        }

        impl<const #d_ident: #d_ty>
            ::core::convert::Into<::core::option::Option<#value_ty>>
            for #name<#d_ident>
        {
            fn into(self) -> ::core::option::Option<#value_ty> {
                if #d_ident == <#d_ty as ::yadc::Dimension>::ZERO {
                    ::core::option::Option::Some(self.0)
                } else {
                    ::core::option::Option::None
                }
            }
        }

        impl<const #qa: #d_ty, const #qb: #d_ty>
            ::core::ops::Mul<#name<#qb>> for #name<#qa>
        where
            #name<{ #qa * #qb }>: Sized,
            ::yadc::Assert<{ #qa.can_mul(#qb) }>: ::yadc::IsTrue,
        {
            type Output = #name<{ #qa * #qb }>;
            fn mul(self, rhs: #name<#qb>) -> Self::Output { #name(self.0 * rhs.0) }
        }

        impl<const #qa: #d_ty, const #qb: #d_ty>
            ::core::ops::Div<#name<#qb>> for #name<#qa>
        where
            #name<{ #qa / #qb }>: Sized,
            ::yadc::Assert<{ #qa.can_div(#qb) }>: ::yadc::IsTrue,
        {
            type Output = #name<{ #qa / #qb }>;
            fn div(self, rhs: #name<#qb>) -> Self::Output { #name(self.0 / rhs.0) }
        }

        impl<const #qa: #d_ty, const #qb: #d_ty>
            ::core::ops::Add<#name<#qb>> for #name<#qa>
        where
            #name<{ #qa + #qb }>: Sized,
            ::yadc::Assert<{ #qa.can_add(#qb) }>: ::yadc::IsTrue,
        {
            type Output = #name<{ #qa + #qb }>;
            fn add(self, rhs: #name<#qb>) -> Self::Output { #name(self.0 + rhs.0) }
        }

        impl<const #qa: #d_ty, const #qb: #d_ty>
            ::core::ops::Sub<#name<#qb>> for #name<#qa>
        where
            #name<{ #qa - #qb }>: Sized,
            ::yadc::Assert<{ #qa.can_sub(#qb) }>: ::yadc::IsTrue,
        {
            type Output = #name<{ #qa - #qb }>;
            fn sub(self, rhs: #name<#qb>) -> Self::Output { #name(self.0 - rhs.0) }
        }

        impl<const #qa: #d_ty, const #qb: #d_ty>
            ::core::ops::AddAssign<#name<#qb>> for #name<#qa>
        where
            ::yadc::Assert<{ #qa.can_add_assign(#qb) }>: ::yadc::IsTrue,
        {
            fn add_assign(&mut self, rhs: #name<#qb>) { self.0 += rhs.0; }
        }
        impl<'__a, const #qa: #d_ty, const #qb: #d_ty>
            ::core::ops::AddAssign<&'__a #name<#qb>> for #name<#qa>
        where
            ::yadc::Assert<{ #qa.can_add_assign(#qb) }>: ::yadc::IsTrue,
        {
            fn add_assign(&mut self, rhs: &'__a #name<#qb>) { self.0 += rhs.0; }
        }
        impl<const #qa: #d_ty, const #qb: #d_ty>
            ::core::ops::SubAssign<#name<#qb>> for #name<#qa>
        where
            ::yadc::Assert<{ #qa.can_sub_assign(#qb) }>: ::yadc::IsTrue,
        {
            fn sub_assign(&mut self, rhs: #name<#qb>) { self.0 -= rhs.0; }
        }
        impl<'__a, const #qa: #d_ty, const #qb: #d_ty>
            ::core::ops::SubAssign<&'__a #name<#qb>> for #name<#qa>
        where
            ::yadc::Assert<{ #qa.can_sub_assign(#qb) }>: ::yadc::IsTrue,
        {
            fn sub_assign(&mut self, rhs: &'__a #name<#qb>) { self.0 -= rhs.0; }
        }

        impl<const #d_ident: #d_ty> ::core::ops::Neg for #name<#d_ident>
        where
            #value_ty: ::core::ops::Neg<Output = #value_ty>,
            ::yadc::Assert<{ #d_ident.can_add_assign(#d_ident) }>: ::yadc::IsTrue,
        {
            type Output = Self;
            fn neg(self) -> Self { #name(-self.0) }
        }

        impl<const #d_ident: #d_ty> ::core::iter::Sum<#name<#d_ident>> for #name<#d_ident>
        where
            ::yadc::Assert<{ #d_ident.can_add_assign(#d_ident) }>: ::yadc::IsTrue,
        {
            fn sum<__I>(iter: __I) -> Self
            where
                __I: ::core::iter::Iterator<Item = #name<#d_ident>>,
            {
                iter.fold(<Self as ::yadc::StaticQuantity>::unit() * #zero_expr, |mut __acc, __q| {
                    __acc += __q;
                    __acc
                })
            }
        }

        impl<'__a, const #d_ident: #d_ty> ::core::iter::Sum<&'__a #name<#d_ident>> for #name<#d_ident>
        where
            ::yadc::Assert<{ #d_ident.can_add_assign(#d_ident) }>: ::yadc::IsTrue,
        {
            fn sum<__I>(iter: __I) -> Self
            where
                __I: ::core::iter::Iterator<Item = &'__a #name<#d_ident>>,
            {
                iter.fold(<Self as ::yadc::StaticQuantity>::unit() * #zero_expr, |mut __acc, __q| {
                    __acc += *__q;
                    __acc
                })
            }
        }

        impl<const #d_ident: #d_ty> ::core::ops::Mul<#value_ty> for #name<#d_ident> {
            type Output = Self;
            fn mul(self, rhs: #value_ty) -> Self { #name(self.0 * rhs) }
        }
        impl<const #d_ident: #d_ty> ::core::ops::Mul<#name<#d_ident>> for #value_ty {
            type Output = #name<#d_ident>;
            fn mul(self, rhs: #name<#d_ident>) -> #name<#d_ident> { #name(self * rhs.0) }
        }
        impl<const #d_ident: #d_ty> ::core::ops::Div<#value_ty> for #name<#d_ident> {
            type Output = Self;
            fn div(self, rhs: #value_ty) -> Self { #name(self.0 / rhs) }
        }
        impl<const #d_ident: #d_ty> ::core::ops::MulAssign<#value_ty> for #name<#d_ident> {
            fn mul_assign(&mut self, rhs: #value_ty) { self.0 *= rhs; }
        }
        impl<const #d_ident: #d_ty> ::core::ops::DivAssign<#value_ty> for #name<#d_ident> {
            fn div_assign(&mut self, rhs: #value_ty) { self.0 /= rhs; }
        }
        impl<const #d_ident: #d_ty>
            ::core::ops::MulAssign<#name<{ <#d_ty as ::yadc::Dimension>::ZERO }>>
            for #name<#d_ident>
        where
            ::yadc::Assert<{
                (#d_ident * <#d_ty as ::yadc::Dimension>::ZERO).dims_eq(#d_ident)
            }>: ::yadc::IsTrue,
        {
            fn mul_assign(&mut self, rhs: #name<{ <#d_ty as ::yadc::Dimension>::ZERO }>) {
                self.0 *= rhs.0;
            }
        }
        impl<const #d_ident: #d_ty>
            ::core::ops::DivAssign<#name<{ <#d_ty as ::yadc::Dimension>::ZERO }>>
            for #name<#d_ident>
        where
            ::yadc::Assert<{
                (#d_ident / <#d_ty as ::yadc::Dimension>::ZERO).dims_eq(#d_ident)
            }>: ::yadc::IsTrue,
        {
            fn div_assign(&mut self, rhs: #name<{ <#d_ty as ::yadc::Dimension>::ZERO }>) {
                self.0 /= rhs.0;
            }
        }
    })
}

// DimensionSerialize / DimensionDeserialize — emit a UCUM-compliant string for
// a Dimension struct. Angle kind → "rad[.axes]", SolidAngle → "sr[.axes]",
// all-zero Linear → "1". Other kinds serialize without a kind annotation;
// the kind is recovered from schema context on deserialize.
/// Derive a UCUM-compliant `serde::Serialize` impl for a Dimension struct.
///
/// Axes are dot-joined with exponents written directly after the symbol
/// (e.g. `s-2`, not `s^-2`). The `#[kind]` field produces a UCUM unit prefix
/// for `Angle` (`"rad"`) and `SolidAngle` (`"sr"`); other kinds produce no
/// annotation. A fully zero dimension serializes as `"1"`.
///
/// ```text
/// "m.kg.s-2"   // Force
/// "K"          // ThermodynamicTemperature (Affine kind not encoded — infer from schema)
/// "K"          // TemperatureInterval (Linear K)
/// "rad"        // Angle
/// "rad.s-1"    // AngularVelocity
/// "sr"         // SolidAngle
/// "1"          // Dimensionless
/// ```
///
/// Pair with [`DimensionDeserialize`](macro@DimensionDeserialize) to
/// round-trip. Both impls are emitted unconditionally — gate them behind a
/// feature in your crate with
/// `#[cfg_attr(feature = "serde", derive(...))]` if serde should be optional.
#[proc_macro_derive(DimensionSerialize)]
pub fn derive_dimension_serialize(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    expand_dimension_serialize(&input)
        .unwrap_or_else(|e| e.to_compile_error())
        .into()
}

// (numeric_fields, kind_field)
// kind_field is (ident, type, annotate) where annotate=true when #[kind(annotate)] is present.
type DimFields = (Vec<(syn::Ident, String)>, Option<(syn::Ident, Type, bool)>);

// Returns (numeric_fields, kind_field) — same shape as expand_dimension.
fn dim_fields(input: &DeriveInput) -> syn::Result<DimFields> {
    let fields = match &input.data {
        Data::Struct(s) => match &s.fields {
            Fields::Named(f) => &f.named,
            _ => {
                return Err(syn::Error::new_spanned(
                    &input.ident,
                    "DimensionSerialize/Deserialize requires a struct with named fields",
                ));
            }
        },
        _ => {
            return Err(syn::Error::new_spanned(
                &input.ident,
                "DimensionSerialize/Deserialize only works on structs",
            ));
        }
    };
    let mut numeric = Vec::new();
    let mut kind: Option<(syn::Ident, Type, bool)> = None;
    for f in fields {
        let kind_attr = f.attrs.iter().find(|a| a.path().is_ident("kind"));
        let Some(id) = f.ident.clone() else {
            continue;
        };
        if let Some(attr) = kind_attr {
            let annotate = matches!(
                &attr.meta,
                syn::Meta::List(list)
                    if matches!(list.parse_args::<syn::Ident>(), Ok(id) if id == "annotate")
            );
            kind = Some((id, f.ty.clone(), annotate));
        } else {
            let s = id.to_string();
            numeric.push((id, s));
        }
    }
    Ok((numeric, kind))
}

fn expand_dimension_serialize(input: &DeriveInput) -> syn::Result<TokenStream2> {
    let name = &input.ident;
    let (axes, kind) = dim_fields(input)?;

    // UCUM kind prefix: "rad" for Angle, "sr" for SolidAngle, nothing otherwise.
    let kind_prefix = match &kind {
        Some((k, kty, _)) => quote! {
            if let ::core::option::Option::Some(__prefix) =
                <#kty as ::yadc::traits::Kind>::ucum_prefix(self.#k)
            {
                __buf.push_str(__prefix);
                __first = false;
            }
        },
        None => quote! {},
    };

    // Axis entries: dot-separated, exponent directly after symbol (UCUM style).
    let axis_entries = axes.iter().map(|(ident, sym)| {
        quote! {
            {
                let __v = self.#ident;
                if __v != 0 {
                    if !__first { __buf.push('.'); }
                    if __v == 1 {
                        __buf.push_str(#sym);
                    } else {
                        let _ = ::core::fmt::Write::write_fmt(
                            &mut __buf,
                            ::core::format_args!("{}{}", #sym, __v),
                        );
                    }
                    __first = false;
                }
            }
        }
    });

    // UCUM annotation suffix {KindName} for non-prefix, non-zero kinds.
    // Only emitted when #[kind(annotate)] is present on the kind field.
    let kind_annotation = match &kind {
        Some((k, kty, true)) => quote! {
            if <#kty as ::yadc::traits::Kind>::ucum_prefix(self.#k).is_none()
                && self.#k != <#kty as ::yadc::traits::Kind>::ZERO
            {
                __buf.push('{');
                __buf.push_str(<#kty as ::yadc::traits::Kind>::name(self.#k));
                __buf.push('}');
            }
        },
        _ => quote! {},
    };

    Ok(quote! {
        const _: () = {
            extern crate alloc as __yadc_alloc;
            impl ::serde::Serialize for #name {
                fn serialize<__S: ::serde::Serializer>(
                    &self,
                    __ser: __S,
                ) -> ::core::result::Result<__S::Ok, __S::Error> {
                    let mut __buf = __yadc_alloc::string::String::new();
                    let mut __first = true;
                    #kind_prefix
                    #(#axis_entries)*
                    // UCUM "1" for a dimensionless/kind-less quantity.
                    if __first { __buf.push('1'); }
                    let _ = __first;
                    #kind_annotation
                    __ser.serialize_str(&__buf)
                }
            }
        };
    })
}

/// Derive a `serde::Deserialize` impl matching
/// [`DimensionSerialize`](macro@DimensionSerialize).
///
/// Parses a UCUM unit string: `"1"` produces the zero dimension; `"rad[.axes]"`
/// sets `Kind::Angle`; `"sr[.axes]"` sets `Kind::SolidAngle`; otherwise axes
/// are parsed from dot-separated tokens with direct exponents (`m2`, `s-2`).
/// Missing axes default to 0; kind defaults to `<Kind>::ZERO` unless a UCUM
/// prefix is present. Unknown unit symbols produce a `serde::de::Error::custom`.
#[proc_macro_derive(DimensionDeserialize)]
pub fn derive_dimension_deserialize(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    expand_dimension_deserialize(&input)
        .unwrap_or_else(|e| e.to_compile_error())
        .into()
}

fn expand_dimension_deserialize(input: &DeriveInput) -> syn::Result<TokenStream2> {
    let name = &input.ident;
    let (axes, kind) = dim_fields(input)?;

    // Sort by symbol length descending so longer symbols are tried first
    // (avoids "m" matching the start of "mol" or "mg").
    let mut sorted_axes = axes.clone();
    sorted_axes.sort_by(|(_, a), (_, b)| b.len().cmp(&a.len()));

    // Generate an if-else chain: for each token, strip the known symbol prefix
    // and parse the remainder as an i8 exponent (empty → 1).
    let parse_chain = sorted_axes.iter().map(|(ident, sym)| {
        let len = sym.len();
        quote! {
            else if __tok.starts_with(#sym) {
                let __exp_str = &__tok[#len..];
                let __exp: i8 = if __exp_str.is_empty() {
                    1i8
                } else {
                    __exp_str.parse::<i8>().map_err(|_| {
                        <__D::Error as ::serde::de::Error>::custom(
                            __yadc_alloc::format!("bad exponent in `{}`", __tok),
                        )
                    })?
                };
                __out.#ident = __exp;
            }
        }
    });

    // When #[kind(annotate)] is present: strip a trailing {KindName} annotation
    // and parse it via serde to recover non-prefix kinds (e.g. "K{Affine}").
    // The remaining string is then processed for UCUM prefix / axes as normal.
    let annotation_extract = match &kind {
        Some((k, kty, true)) => quote! {
            let __s: &str = if __s.ends_with('}') {
                if let ::core::option::Option::Some(__open) = __s.rfind('{') {
                    let __ann = &__s[__open + 1..__s.len() - 1];
                    let __kind_de =
                        ::serde::de::value::StrDeserializer::<__D::Error>::new(__ann);
                    __out.#k = <#kty as ::serde::Deserialize>::deserialize(__kind_de)
                        .map_err(|_| {
                            <__D::Error as ::serde::de::Error>::custom(
                                __yadc_alloc::format!("unknown kind `{}`", __ann),
                            )
                        })?;
                    __s[..__open].trim_end()
                } else {
                    &__s
                }
            } else {
                &__s
            };
        },
        _ => quote! { let __s: &str = &__s; },
    };

    // Kind prefix detection: "1" → dimensionless, "rad[.]" → Angle,
    // "sr[.]" → SolidAngle.  When there is no #[kind] field, skip entirely.
    let kind_prefix_extract = match &kind {
        Some((k, kty, _)) => quote! {
            let __axes: &str =
                if __s == "1" {
                    return ::core::result::Result::Ok(__out);
                } else if __s == "rad" {
                    __out.#k = <#kty as ::yadc::traits::Kind>::ANGLE;
                    return ::core::result::Result::Ok(__out);
                } else if __s.starts_with("rad.") {
                    __out.#k = <#kty as ::yadc::traits::Kind>::ANGLE;
                    &__s[4..]
                } else if __s == "sr" {
                    __out.#k = <#kty as ::yadc::traits::Kind>::SOLID_ANGLE;
                    return ::core::result::Result::Ok(__out);
                } else if __s.starts_with("sr.") {
                    __out.#k = <#kty as ::yadc::traits::Kind>::SOLID_ANGLE;
                    &__s[3..]
                } else {
                    &__s
                };
        },
        None => quote! {
            let __axes: &str =
                if __s == "1" { return ::core::result::Result::Ok(__out); }
                else { __s };
        },
    };

    Ok(quote! {
        const _: () = {
            extern crate alloc as __yadc_alloc;
            impl<'de> ::serde::Deserialize<'de> for #name {
                fn deserialize<__D: ::serde::Deserializer<'de>>(
                    __de: __D,
                ) -> ::core::result::Result<Self, __D::Error> {
                    let __s: __yadc_alloc::string::String =
                        <__yadc_alloc::string::String as ::serde::Deserialize>::deserialize(__de)?;
                    let mut __out = <#name as ::yadc::Dimension>::ZERO;
                    #annotation_extract
                    #kind_prefix_extract
                    for __tok in __axes.split('.') {
                        if false { unreachable!() }
                        #(#parse_chain)*
                        else {
                            return ::core::result::Result::Err(
                                <__D::Error as ::serde::de::Error>::custom(
                                    __yadc_alloc::format!("unknown unit `{}`", __tok),
                                ),
                            );
                        }
                    }
                    ::core::result::Result::Ok(__out)
                }
            }
        };
    })
}

/// Derive [`DynamicQuantity`](::yadc::DynamicQuantity) and runtime-dim arithmetic
/// for a named-field struct carrying a value and a dimension.
///
/// Requires `#[static_quantity(Qty)]` naming the companion static quantity type.
/// The value field is identified by a `#[value]` attribute or by the name
/// `value`; the dim field is identified by a `#[dim]` attribute or by the
/// name `dim`. Emits:
/// - `DynamicQuantity` trait impl (`type D`, `type V`).
/// - `Into<Option<V>>` — `Some(v)` when dimensionless, `None` otherwise.
/// - `Mul`/`Div` (always succeed — dims combine via the user's
///   [`Dim`](macro@Dimension) tables).
/// - `Add`/`Sub` (return `Option`; `None` on dim mismatch).
/// - Scalar `Mul<V>` / `Div<V>`.
/// - `From<Qty<D>> for DynQty` and `TryFrom<DynQty> for Qty<D>`.
///
/// ```ignore
/// #[derive(Copy, Clone, PartialEq, DynamicQuantity)]
/// #[static_quantity(Qty)]
/// pub struct DynQty {
///     value: f64,
///     dim: Dim,
/// }
///
/// // Custom field names via marker attributes:
/// #[derive(Copy, Clone, PartialEq, DynamicQuantity)]
/// #[static_quantity(Qty)]
/// pub struct DynQty {
///     #[value] v: f64,
///     #[dim]   d: Dim,
/// }
/// ```
#[proc_macro_derive(DynamicQuantity, attributes(static_quantity, value, dim))]
pub fn derive_dynamic_quantity(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    expand_dyn_quantity(&input)
        .unwrap_or_else(|e| e.to_compile_error())
        .into()
}

fn expand_dyn_quantity(input: &DeriveInput) -> syn::Result<TokenStream2> {
    let name = &input.ident;

    let qty_ty = find_attr_type(input, "static_quantity")?.ok_or_else(|| {
        syn::Error::new_spanned(
            name,
            "missing #[static_quantity(QtyType)] on DynamicQuantity struct",
        )
    })?;

    let (val_ident, value_ty, dim_ident, dims_ty) = named_value_dims_fields(&input.data, name)?;

    let d = syn::Ident::new("__D", Span::call_site());
    let d_ty = &dims_ty;

    Ok(quote! {
        impl ::core::convert::Into<::core::option::Option<#value_ty>> for #name {
            // Returns Some only for dimensionless quantities (dim == D::ZERO).
            fn into(self) -> ::core::option::Option<#value_ty> {
                if self.#dim_ident == <#d_ty as ::yadc::Dimension>::ZERO {
                    ::core::option::Option::Some(self.#val_ident)
                } else {
                    ::core::option::Option::None
                }
            }
        }

        impl ::yadc::DynamicQuantity for #name {
            type D = #d_ty;
            type V = #value_ty;
        }

        impl ::core::ops::Mul for #name {
            type Output = #name;
            fn mul(self, rhs: #name) -> #name {
                #name {
                    #val_ident: self.#val_ident * rhs.#val_ident,
                    #dim_ident: self.#dim_ident * rhs.#dim_ident,
                }
            }
        }
        impl ::core::ops::Div for #name {
            type Output = #name;
            fn div(self, rhs: #name) -> #name {
                #name {
                    #val_ident: self.#val_ident / rhs.#val_ident,
                    #dim_ident: self.#dim_ident / rhs.#dim_ident,
                }
            }
        }

        impl ::core::ops::Add for #name {
            type Output = ::core::option::Option<#name>;
            fn add(self, rhs: #name) -> ::core::option::Option<#name> {
                use ::yadc::Dimension as _;
                self.#dim_ident.can_add(rhs.#dim_ident).then(|| #name {
                    #val_ident: self.#val_ident + rhs.#val_ident,
                    #dim_ident: self.#dim_ident + rhs.#dim_ident,
                })
            }
        }
        impl ::core::ops::Sub for #name {
            type Output = ::core::option::Option<#name>;
            fn sub(self, rhs: #name) -> ::core::option::Option<#name> {
                use ::yadc::Dimension as _;
                self.#dim_ident.can_sub(rhs.#dim_ident).then(|| #name {
                    #val_ident: self.#val_ident - rhs.#val_ident,
                    #dim_ident: self.#dim_ident - rhs.#dim_ident,
                })
            }
        }

        impl ::core::ops::Mul<#value_ty> for #name {
            type Output = #name;
            fn mul(self, rhs: #value_ty) -> #name {
                #name { #val_ident: self.#val_ident * rhs, #dim_ident: self.#dim_ident }
            }
        }
        impl ::core::ops::Div<#value_ty> for #name {
            type Output = #name;
            fn div(self, rhs: #value_ty) -> #name {
                #name { #val_ident: self.#val_ident / rhs, #dim_ident: self.#dim_ident }
            }
        }

        impl<const #d: #d_ty> ::core::convert::From<#qty_ty<#d>> for #name {
            fn from(q: #qty_ty<#d>) -> Self {
                Self { #val_ident: q.0, #dim_ident: #d }
            }
        }
        impl<const #d: #d_ty> ::core::convert::TryFrom<#name> for #qty_ty<#d> {
            type Error = ();
            fn try_from(dyn_qty: #name) -> ::core::result::Result<#qty_ty<#d>, ()> {
                if dyn_qty.#dim_ident == #d {
                    ::core::result::Result::Ok(<#qty_ty<#d>>::unit() * dyn_qty.#val_ident)
                } else {
                    ::core::result::Result::Err(())
                }
            }
        }

    })
}

fn single_tuple_field(data: &Data, span: &impl quote::ToTokens) -> syn::Result<Type> {
    match data {
        Data::Struct(s) => match &s.fields {
            Fields::Unnamed(f) if f.unnamed.len() == 1 => Ok(f.unnamed.first().unwrap().ty.clone()),
            _ => Err(syn::Error::new_spanned(
                span,
                "expected a single-field tuple struct, e.g. struct Qty<const D: Dims>(f64)",
            )),
        },
        _ => Err(syn::Error::new_spanned(
            span,
            "#[derive(Qty)] only works on structs",
        )),
    }
}

fn single_const_param<'a>(
    generics: &'a syn::Generics,
    span: &impl quote::ToTokens,
) -> syn::Result<(&'a syn::Ident, &'a Type)> {
    let mut first = None;
    for p in &generics.params {
        if let GenericParam::Const(c) = p {
            if c.attrs.iter().any(|a| a.path().is_ident("dim")) {
                return Ok((&c.ident, &c.ty));
            }
            first.get_or_insert(c);
        }
    }
    match first {
        Some(c) => Ok((&c.ident, &c.ty)),
        None => Err(syn::Error::new_spanned(
            span,
            "expected one const generic parameter, e.g. `#[dim] const D: MyDim`",
        )),
    }
}

// Returns (value_ident, value_ty, dim_ident, dim_ty).
// Fields are discovered by a `#[value]` / `#[dim]` marker attribute first,
// then by name (`"value"` / `"dim"`) as a fallback.
fn named_value_dims_fields(
    data: &Data,
    span: &impl quote::ToTokens,
) -> syn::Result<(syn::Ident, Type, syn::Ident, Type)> {
    let fields = match data {
        Data::Struct(s) => match &s.fields {
            Fields::Named(f) => f,
            _ => {
                return Err(syn::Error::new_spanned(
                    span,
                    "#[derive(DynamicQuantity)] requires a named-field struct",
                ));
            }
        },
        _ => {
            return Err(syn::Error::new_spanned(
                span,
                "#[derive(DynamicQuantity)] only works on structs",
            ));
        }
    };

    let mut val_field: Option<(syn::Ident, Type)> = None;
    let mut dim_field: Option<(syn::Ident, Type)> = None;

    for f in &fields.named {
        let Some(ident) = f.ident.clone() else {
            continue;
        };
        let has_value = f.attrs.iter().any(|a| a.path().is_ident("value"));
        let has_dim = f.attrs.iter().any(|a| a.path().is_ident("dim"));
        if has_value {
            val_field = Some((ident.clone(), f.ty.clone()));
        }
        if has_dim {
            dim_field = Some((ident, f.ty.clone()));
        }
    }

    // Name-based fallback (only when no attribute marked the field).
    if val_field.is_none() {
        val_field = fields
            .named
            .iter()
            .find(|f| f.ident.as_ref().map(|i| i == "value").unwrap_or(false))
            .map(|f| (f.ident.clone().unwrap(), f.ty.clone()));
    }
    if dim_field.is_none() {
        dim_field = fields
            .named
            .iter()
            .find(|f| f.ident.as_ref().map(|i| i == "dim").unwrap_or(false))
            .map(|f| (f.ident.clone().unwrap(), f.ty.clone()));
    }

    let (val_ident, val_ty) = val_field.ok_or_else(|| {
        syn::Error::new_spanned(
            span,
            "no `#[value]` field and no field named `value` on DynamicQuantity struct",
        )
    })?;
    let (dim_ident, dim_ty) = dim_field.ok_or_else(|| {
        syn::Error::new_spanned(
            span,
            "no `#[dim]` field and no field named `dim` on DynamicQuantity struct",
        )
    })?;

    Ok((val_ident, val_ty, dim_ident, dim_ty))
}

fn find_attr_type(input: &DeriveInput, attr_name: &str) -> syn::Result<Option<syn::Path>> {
    for attr in &input.attrs {
        if attr.path().is_ident(attr_name) {
            return Ok(Some(attr.parse_args::<syn::Path>()?));
        }
    }
    Ok(None)
}

type UnitAttr = (Expr, String, Option<Expr>, Option<String>);

fn find_unit_attr(variant: &syn::Variant) -> syn::Result<Option<UnitAttr>> {
    for attr in &variant.attrs {
        if attr.path().is_ident("unit") {
            let (mult, symbol, offset, long) = attr.parse_args_with(parse_unit_args)?;
            return Ok(Some((
                mult,
                symbol.value(),
                offset,
                long.map(|s| s.value()),
            )));
        }
    }
    Ok(None)
}

fn parse_unit_args(
    input: ParseStream<'_>,
) -> syn::Result<(Expr, LitStr, Option<Expr>, Option<LitStr>)> {
    let mult: Expr = input.parse()?;
    input.parse::<Token![,]>()?;
    let symbol: LitStr = input.parse()?;

    let mut offset: Option<Expr> = None;
    let mut long: Option<LitStr> = None;
    while input.peek(Token![,]) {
        input.parse::<Token![,]>()?;
        if input.is_empty() {
            break;
        }
        if input.peek(syn::Ident) && input.peek2(Token![=]) {
            let kw: syn::Ident = input.parse()?;
            input.parse::<Token![=]>()?;
            match kw.to_string().as_str() {
                "offset" => offset = Some(input.parse()?),
                "long" => long = Some(input.parse()?),
                other => {
                    return Err(syn::Error::new(
                        kw.span(),
                        format!("unknown #[unit] arg `{other}`; expected `offset` or `long`"),
                    ));
                }
            }
        } else if input.peek(LitStr) {
            long = Some(input.parse()?);
        } else {
            offset = Some(input.parse()?);
        }
    }

    Ok((mult, symbol, offset, long))
}
